language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - cd backend
  - python manage.py makemigrations file judge problem submission user
  - python manage.py migrate
  - python manage.py test